CLINICAL_TRIALS_ID = "id"
CLINICAL_TRIALS_SCIENTIFIC_TITLE = "scientific_title"
CLINICAL_TRIALS_DATE = "date"
CLINICAL_TRIALS_JOURNAL = "journal"

DRUGS_ATCCODE = "atccode"
DRUGS_NAME = "drug"

PUBMED_ID = "id"
PUBMED_TITLE = "title"
PUBMED_DATE = "date"
PUBMED_JOURNAL = "journal"

JOURNAL = "journal"
